<?php
/**
 * TL_ROOT/system/modules/recommendation/languages/nl/default.php 
 * 
 * Contao extension: recommendation 1.0.2 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Peter Hamers (pchammer) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['recommendation']['0'] = "Recommendation";
$GLOBALS['TL_LANG']['CTE']['recommendation']['1'] = "Dit element bevat een hyperlink welke e-mail opent om een pagina aan te bevelen aan een vriend.";
 
?>
