<?php
/**
 * TL_ROOT/system/modules/recommendation/languages/nl/tl_content.php 
 * 
 * Contao extension: recommendation 1.0.2 stable 
 * Dutch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Peter Hamers (pchammer) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['recommendation_linktext']['0'] = "Link tekst";
$GLOBALS['TL_LANG']['tl_content']['recommendation_linktext']['1'] = "Geef de tekst op welke als hyperlink dient om de pagina aan te bevelen.";
$GLOBALS['TL_LANG']['tl_content']['recommendation_subject']['0'] = "Mail onderwerp";
$GLOBALS['TL_LANG']['tl_content']['recommendation_subject']['1'] = "Geef een onderwerp op voor de recommendation mail.";
$GLOBALS['TL_LANG']['tl_content']['recommendation_body']['0'] = "Mail body";
$GLOBALS['TL_LANG']['tl_content']['recommendation_body']['1'] = "Geef de mail body op van recommendation mail.";
$GLOBALS['TL_LANG']['tl_content']['recommendation_linktext_text'] = "Pagina doorsturen naar een vriend";
$GLOBALS['TL_LANG']['tl_content']['recommendation_subject_text'] = "Interessante web pagina om te bekijken";
$GLOBALS['TL_LANG']['tl_content']['recommendation_body_text'] = "Ik heb een web pagina gevonden %s deze is wellicht interessant voor jou.";
$GLOBALS['TL_LANG']['tl_content']['recommendation_enter_recipient'] = "Geef e-mail adres op van de ontvanger";
$GLOBALS['TL_LANG']['tl_content']['recommendation_legend'] = "Recommendation instellingen";
 
?>
