<?php
/**
 * TL_ROOT/system/modules/recommendation/languages/de/default.php 
 * 
 * TYPOlight extension: recommendation 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['CTE']['recommendation']['0'] = "Empfehlung";
$GLOBALS['TL_LANG']['CTE']['recommendation']['1'] = "Dieses Element erstellt einen Hyperlink, der eine E-Mail erzeugt, mit der man die aktuelle Seite an eine andere Person empfehlen kann.";
 
?>
