<?php
/**
 * TL_ROOT/system/modules/recommendation/languages/de/tl_content.php 
 * 
 * TYPOlight extension: recommendation 1.0.1 stable 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['recommendation_linktext']['0'] = "Titel des Links";
$GLOBALS['TL_LANG']['tl_content']['recommendation_linktext']['1'] = "Der Titel wird den Besuchern der Webseite anstelle der Zieladresse angezeigt.";
$GLOBALS['TL_LANG']['tl_content']['recommendation_subject']['0'] = "Betreff der E-Mail";
$GLOBALS['TL_LANG']['tl_content']['recommendation_subject']['1'] = "Bitte geben Sie einen Betreff für die E-Mail Benachrichtung ein.";
$GLOBALS['TL_LANG']['tl_content']['recommendation_body']['0'] = "Inhalt";
$GLOBALS['TL_LANG']['tl_content']['recommendation_body']['1'] = "Bitte geben Sie einen Text mit dem Platzhalter %s für den Inhalt der E-Mail Benachrichtigung ein. Der Platzhalter %s wird automatisch mit der URL zur aktuellen Seite ersetzt.";
$GLOBALS['TL_LANG']['tl_content']['recommendation_linktext_text'] = "Empfehlen Sie diese Seite";
$GLOBALS['TL_LANG']['tl_content']['recommendation_subject_text'] = "Seitenempfehlung";
$GLOBALS['TL_LANG']['tl_content']['recommendation_body_text'] = "Ich denke, diese Website solltest du dir wirklich ansehen: %s";
$GLOBALS['TL_LANG']['tl_content']['recommendation_enter_recipient'] = "E-Mail Adresse des Empfängers";
$GLOBALS['TL_LANG']['tl_content']['recommendation_legend'] = "Empfehlungs-Einstellungen";
 
?>
